Button Component added
christianahvilla/werden-ui pull request #6
Opened 2022-10-28 17:06 UTC by PedroAGC

**Background**

Used to show a tree-structured data.

**Changes done**

- Add Tree Component
- Add Story
- Add Type

2022-10-29 22:32 UTC, christianahvilla requested changes
Overall looks good, just few comments please fixed before merge this PR

2022-10-29 22:32 UTC, christianahvilla commented on src/stories/WButton/WButton.tsx
> +export default WButton
```suggestion
import Button from 'rsuite/Button';
import { IWButton } from './types';

const WButton = (props: IWButton) => {
  if(!props){
    return null
  }

  return (
    <Button {...props}>{props.text}</Button>
  );
};

export default WButton
```

2022-10-29 22:32 UTC, christianahvilla commented on src/stories/WButton/types.ts
> +  onClick?: () => void;
Sort the interface keys

2022-11-01 18:08 UTC, PedroAGC commented on src/stories/WButton/WButton.tsx
> +export default WButton
Fixed!

2022-11-01 18:08 UTC, PedroAGC commented on src/stories/WButton/types.ts
> +  onClick?: () => void;
Sorted!

2022-11-01 18:29 UTC, christianahvilla approved these changes
LGTM

2022-11-01 18:29 UTC, merged